### ISSUE TITLE
Using without Sponge

### ISSUE THREAD

**Issue by Smurfboi007** [Pixelmon-Development/Pixelmon-Mixins#8]
Running Mohist, this would literally be a life saver. Or actually not literally, but still a life saver.

```
[13:32:55] [main/DEBUG] [FML]: Examining for coremod candidacy PixelmonFixes-0.4.0.jar
[13:32:55] [main/INFO] [FML]: Loading tweaker org.spongepowered.asm.launch.MixinTweaker from PixelmonFixes-0.4.0.jar
[13:32:55] [main/DEBUG] [FML]: Examining for coremod candidacy ThePixelmonOST.zip
[13:32:55] [main/DEBUG] [FML]: Examining for coremod candidacy TrainerCommands-1.12.2-2.5.1-universal.jar
[13:32:55] [main/DEBUG] [FML]: Not found coremod data in TrainerCommands-1.12.2-2.5.1-universal.jar
[13:32:55] [main/DEBUG] [FML]: Examining for coremod candidacy WonderTrade-1.12.2-4.6.3-universal.jar
[13:32:55] [main/DEBUG] [FML]: Not found coremod data in WonderTrade-1.12.2-4.6.3-universal.jar
[13:32:55] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[13:32:55] [main/INFO] [LaunchWrapper]: Loading tweak class name org.spongepowered.asm.launch.MixinTweaker
[13:32:55] [main/ERROR] [LaunchWrapper]: Unable to launch
java.lang.ClassNotFoundException: org.spongepowered.asm.launch.MixinTweaker
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_252]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_252]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352) ~[?:1.8.0_252]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_252]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:106) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_252]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_252]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_252]
	at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_252]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:98) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_252]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_252]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_252]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_252]
	at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:72) [server.jar:?]
	at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:37) [server.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_252]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_252]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_252]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_252]
	at com.mohistmc.MohistMC.main(MohistMC.java:66) [server.jar:1.12.2-320]
```

**Comment by zandathebigbluepanda** [comment]
works with a mixin loader and magma/mohist like mixin booter
